SCHEMA_FIELDS: dict[str, list[str]] = {
    "users": [
        "username",
        "password",
        "role",
        "fullName",
        "dateOfBirth",
        "gender",
        "email",
        "phoneNumber",
        "rewardPoints",
        "membershipLevel",
    ],
    "cinemas": ["name", "city", "address", "rooms"],
    "movies": ["title", "genres", "description", "durationMin", "releaseDate", "status"],
    "showtimes": ["movieId", "cinemaId", "roomId", "startTime", "endTime", "basePrice", "status", "bookedSeats"],
    "bookings": [
        "bookingCode",
        "userId",
        "staffId",
        "showtimeId",
        "bookingTime",
        "paymentMethod",
        "promotionCode",
        "totalPrice",
        "tickets",
    ],
    "reviews": ["movieId", "userId", "rating", "comment", "reviewedAt"],
    "service_requests": ["userId", "requestType", "requestDetail", "status"],
}
